version: "2.2"
services:
  crawler:
    container_name: "crawler"
    hostname: "crawler"
    build:
      context: .
      dockerfile: Dockerfile.crawler
    networks:
      - net
    volumes:
      - ./model:/model
    command: ["python", "main.py"]

networks:
  net:
    external: true

volumes:
  model:
    driver: local
