FROM python:3.6.10
RUN apt-get install -y git
COPY ./crawler/requirements.txt ./
COPY ./crawler ./
COPY wait-for-it.sh /wait-for-it.sh
# RUN git clone --depth=1 https://github.com/twintproject/twint.git && \
#     cd twint && \
#     pip install . -r requirements.txt
RUN pip install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint
RUN pip install -r requirements.txt
RUN python -m spacy download fr_core_news_sm